# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9dd71621228723b46ff2d7caa0b1e6bad92a09536e6502a22e61cd60f43554410f0126c0d9426de0683e68c1fb8150ba446cbcb8ea1bcd054c0042c3bd0c4e80

test:
  secret_key_base: 2548f23f3240744fa0cf564e7d9a88e4c1e1ee1feff749611732b822e49ac7ec1c28eb5f763fac6293d1b94604d67acb27d493c430f2d8ac9e88f172d5f0d098

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
